#!/usr/bin/env bash

script_name=${0##*/}
BTFHUB_CACHE_DIR="${BTFHUB_CACHE:-$HOME/.cache/eunomia/btfhub}"
BTFHUB_REPO_URL="${BTFHUB_REPO:-https://github.com/aquasecurity/btfhub-archive}"
usage() {
	cat <<-EOF
	Usage:
	  ${script_name} [-h|--help]
	    print this help message

	  ${script_name} [btfgen] [OPTIONS] BPF[.o]
      Create reduced version of BTF files to be embedded within the tools executables

	  ${script_name} [fetch]
      fetch btfhub-archive from github and save to DIR
      DIR default is "${HOME}/.cache/eunomia/btfhub" or you can set "\$BTFHUB_CACHE" to override

	Options:
	  btfgen options:
      -j, --json JSON_FILE  compress tar.gz with package.json
	EOF
}

fetch() {
  command -v git     >/dev/null 2>&1 || { echo "Error: git is not installed." >&2; exit 1; }
  if [ -d "$BTFHUB_CACHE_DIR" ]; then
    echo "BTFHUB_CACHE_DIR does exist, skip fetch"
    return
  fi

  mkdir -p $(dirname ${BTFHUB_CACHE_DIR})
  git clone --depth 1 ${BTFHUB_REPO_URL} ${BTFHUB_CACHE_DIR}
}

btfgen() {
  fetch
  command -v bpftool >/dev/null 2>&1 || { echo "Error: bpftool is not installed." >&2; exit 1; }
  short_args="j:f"
	long_args="json:,file:"
	TEMP=$(getopt -o "$short_args" --long "$long_args" -n "$script_name" -- "$@") \
		|| return 1
	eval set -- "$TEMP";

	local json file
	while [[ ${1:0:1} == - ]]; do
		[[ $1 =~ ^-f|--|--file$ ]] && {
			shift 1;
			if [ -n "$1" ]; then file="$1"; shift 1; continue; fi
		};
		[[ $1 =~ ^-j|--json$ ]]    && { json="$2"; shift 2; continue; };
		break;
	done

  dir=$(pwd)
  find $BTFHUB_CACHE_DIR -name "*.tar.xz" | \
  xargs -P 8 -I fileName sh -c 'tar xvfJ "fileName" -C "$(dirname "fileName")"'
  find $BTFHUB_CACHE_DIR -name "*.btf" | \
  xargs -P 8 -I fileName sh -c 'bpftool gen min_core_btf "fileName" "fileName" '$file''

  if [ -z "$json" ]; then cp $json $BTFHUB_CACHE_DIR; fi

  cd $BTFHUB_CACHE_DIR && tar --exclude="*.xz" -czvf $dir/output.tar.gz .
}

main() {
	action="$1"
	shift
	case "$action" in
		(btfgen) btfgen "$@";;
		(fetch) fetch "$@";;
		(-h|--help) usage;;
		(*) echo "no action given. try '$script_name' -h for more information"
	esac
}

main "$@"
